name: Copy File to Pod Persistent Volume

on:
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get file path and pod name (replace with your input logic)
        id: get_inputs
        run: echo "path/to/your/file.txt"
         
